name: Publish devcontainers
on:
  push:
    branches:
      - main

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into registry Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/the-bds-maneger/devcontainer_base:latest
          platforms: linux/arm64,linux/amd64
          cache-from: type=gha,scope=${{ github.ref }}_${{ github.repo }}
          cache-to: type=gha,mode=max,scope=${{ github.ref }}_${{ github.repo }}

  nodejs:
    runs-on: ubuntu-latest
    needs:
      - base
    steps:
      - uses: actions/checkout@v3.0.1
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into registry Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          context: ./node
          push: true
          tags: ghcr.io/the-bds-maneger/devcontainer_nodejs:latest
          platforms: linux/arm64,linux/amd64
          cache-from: type=gha,scope=${{ github.ref }}_${{ github.repo }}
          cache-to: type=gha,mode=max,scope=${{ github.ref }}_${{ github.repo }}